description: This component scrapes the contact information of financial advisors
  from the Morgan Stanley website. It uses BeautifulSoup and requests library to navigate,
  find and extract the data.
input-class: ScraperInput
name: MorganStanleyScraper
output-class: ContactInformation
parameters: {}
